<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-19T15:04:47 IST" name="Default suite" finished-at="2023-01-19T15:05:40 IST" duration-ms="53089">
    <groups>
    </groups>
    <test started-at="2023-01-19T15:04:47 IST" name="Default test" finished-at="2023-01-19T15:05:40 IST" duration-ms="53089">
      <class name="com.datadriventest.DataDrivenTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.datadriventest.DataDrivenTest@3b96c42e]" started-at="2023-01-19T15:04:47 IST" name="setup" finished-at="2023-01-19T15:05:03 IST" duration-ms="15881" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.datadriventest.DataDrivenTest@3b96c42e]" started-at="2023-01-19T15:05:03 IST" name="loginTest" data-provider="Credentials1" finished-at="2023-01-19T15:05:13 IST" duration-ms="9941" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[nishigandhazine@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nishi@1996]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.datadriventest.DataDrivenTest@3b96c42e]" started-at="2023-01-19T15:05:13 IST" name="tearDown" finished-at="2023-01-19T15:05:14 IST" duration-ms="888" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.datadriventest.DataDrivenTest@3b96c42e]" started-at="2023-01-19T15:05:14 IST" name="setup" finished-at="2023-01-19T15:05:27 IST" duration-ms="13003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.datadriventest.DataDrivenTest@3b96c42e]" started-at="2023-01-19T15:05:27 IST" name="loginTest" data-provider="Credentials1" finished-at="2023-01-19T15:05:39 IST" duration-ms="12171" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nishigandhazine@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nishi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.apps.dalalstreet.ai/dashboard] but found [https://www.apps.dalalstreet.ai/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.apps.dalalstreet.ai/dashboard] but found [https://www.apps.dalalstreet.ai/login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.datadriventest.DataDrivenTest.loginTest(DataDrivenTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.datadriventest.DataDrivenTest@3b96c42e]" started-at="2023-01-19T15:05:39 IST" name="tearDown" finished-at="2023-01-19T15:05:40 IST" duration-ms="1068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.datadriventest.DataDrivenTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
